const copy = {
    en: {
        appName: "WordSketch",
        translateTab: "Translate",
        studyTab: "Flashcards",
        swap: "Swap",
        phraseLabel: "Phrase",
        phrasePlaceholderEn: "Type in English",
        phrasePlaceholderHe: "Type in Hebrew",
        translationPlaceholder: "Translation",
        translateAction: "Translate",
        translating: "Translating...",
        addFlashcard: "+ Flashcard",
        addingFlashcard: "Creating flashcard...",
        flashcardReady: "Saved to your deck",
        flashcardRemoved: "Removed from flashcards",
        suggestionAdded: "Suggestion added to flashcards",
        mockBanner: "Mock AI mode is on.",
        studyHeading: "Flashcards",
        studyEmpty: "No flashcards yet. Add a phrase from the translation panel to start studying.",
        showAnswer: "Guess",
        gotIt: "Got it!",
        oops: "Oops",
        aiModeMock: "Mock mode",
        suggestionsHeading: "Suggested next",
        suggestionsCaption: "Based on your last five additions",
        suggestionsModalTitle: "Get suggestions",
        loadingSuggestions: "Finding related words...",
        suggestionsEmpty: "Add a few flashcards and related words will appear here.",
        addSuggestion: "Add",
        removeFlashcard: "Remove from pool",
        flashcardScore: "Score",
        getSuggestions: "Get suggestions",
        close: "Close",
        learnedWords: "Learned",
        authTitle: "Welcome to Oolpan",
        authLoginTab: "Log in",
        authRegisterTab: "Create account",
        authUsernameLabel: "Username",
        authUsernamePlaceholder: "Choose a username",
        authPasswordLabel: "Password",
        authPasswordPlaceholder: "Enter your password",
        authRegisterHint: "We’ll create your account and generate a default password for future logins.",
        authCreateAction: "Create account",
        authCreating: "Creating account...",
        authLoginAction: "Log in",
        authLoggingIn: "Logging in...",
        authLogout: "Log out",
        authPasswordNotice: "Default password",
        authPasswordDismiss: "Got it",
        authSignedInAs: "Signed in as",
        authSessionExpired: "Please log in again"
    },
    he: {
        appName: "WordSketch",
        translateTab: "תרגום",
        studyTab: "כרטיסיות",
        swap: "החלפה",
        phraseLabel: "ביטוי",
        phrasePlaceholderEn: "הקלד או הקלידי באנגלית",
        phrasePlaceholderHe: "הקלד או הקלידי בעברית",
        translationPlaceholder: "תרגום",
        translateAction: "תרגום",
        translating: "מתרגם...",
        addFlashcard: "+ כרטיסייה",
        addingFlashcard: "יוצר כרטיסייה...",
        flashcardReady: "נשמר בחפיסה",
        flashcardRemoved: "הוסר מהכרטיסיות",
        suggestionAdded: "ההצעה נוספה לכרטיסיות",
        mockBanner: "מצב דמה פעיל.",
        studyHeading: "כרטיסיות",
        studyEmpty: "עדיין אין כרטיסיות. אפשר להוסיף ביטוי מלוח התרגום כדי להתחיל.",
        showAnswer: "ניחוש",
        gotIt: "יש!",
        oops: "לא בדיוק",
        aiModeMock: "מצב דמה",
        suggestionsHeading: "הצעות להמשך",
        suggestionsCaption: "מבוסס על חמש ההוספות האחרונות",
        suggestionsModalTitle: "קבלת הצעות",
        loadingSuggestions: "מחפש מילים קשורות...",
        suggestionsEmpty: "אחרי שמוסיפים כמה כרטיסיות, יופיעו כאן הצעות קשורות.",
        addSuggestion: "הוספה",
        removeFlashcard: "הסרה מהחפיסה",
        flashcardScore: "ציון",
        getSuggestions: "קבלת הצעות",
        close: "סגירה",
        learnedWords: "נלמדו",
        authTitle: "ברוכים הבאים ל-Oolpan",
        authLoginTab: "כניסה",
        authRegisterTab: "יצירת חשבון",
        authUsernameLabel: "שם משתמש",
        authUsernamePlaceholder: "בחרו שם משתמש",
        authPasswordLabel: "סיסמה",
        authPasswordPlaceholder: "הזינו סיסמה",
        authRegisterHint: "ניצור את החשבון ונפיק סיסמת ברירת מחדל לכניסות עתידיות.",
        authCreateAction: "יצירת חשבון",
        authCreating: "יוצר חשבון...",
        authLoginAction: "כניסה",
        authLoggingIn: "נכנס...",
        authLogout: "התנתקות",
        authPasswordNotice: "סיסמת ברירת מחדל",
        authPasswordDismiss: "הבנתי",
        authSignedInAs: "מחובר בתור",
        authSessionExpired: "צריך להתחבר שוב"
    }
};
export function t(language, key) {
    return copy[language][key] ?? key;
}
