import type { AppLanguage } from "@study/shared";

type Dictionary = Record<string, string>;

const copy: Record<AppLanguage, Dictionary> = {
  en: {
    appName: "WordSketch",
    translateTab: "Translate",
    studyTab: "Flashcards",
    swap: "Swap",
    phraseLabel: "Phrase",
    phrasePlaceholderEn: "Type in English",
    phrasePlaceholderHe: "Type in Hebrew",
    translationPlaceholder: "Translation",
    translateAction: "Translate",
    translating: "Translating...",
    addFlashcard: "+ Flashcard",
    addingFlashcard: "Creating flashcard...",
    flashcardReady: "Saved to your deck",
    flashcardRemoved: "Removed from flashcards",
    suggestionAdded: "Suggestion added to flashcards",
    mockBanner: "Mock AI mode is on.",
    studyHeading: "Flashcards",
    studyEmpty: "No flashcards yet. Add a phrase from the translation panel to start studying.",
    showAnswer: "Guess",
    gotIt: "Got it!",
    oops: "Oops",
    aiModeMock: "Mock mode",
    suggestionsHeading: "Suggested next",
    suggestionsCaption: "Based on your last five additions",
    suggestionsModalTitle: "Get suggestions",
    loadingSuggestions: "Finding related words...",
    suggestionsEmpty: "Add a few flashcards and related words will appear here.",
    addSuggestion: "Add",
    removeFlashcard: "Remove from pool",
    flashcardScore: "Score",
    flashcardImageCue: "Image cue",
    playAudio: "Play AI audio",
    autoSpeakHebrew: "Auto-speak Hebrew",
    getSuggestions: "Get suggestions",
    close: "Close",
    learnedWords: "Learned",
    authTitle: "Welcome to Oolpan",
    authLoginTab: "Log in",
    authRegisterTab: "Create account",
    authUsernameLabel: "Username",
    authUsernamePlaceholder: "Choose a username",
    authPasswordLabel: "Password",
    authPasswordPlaceholder: "Enter your password",
    authRegisterHint: "We’ll create your account and generate a default password for future logins.",
    authCreateAction: "Create account",
    authCreating: "Creating account...",
    authLoginAction: "Log in",
    authLoggingIn: "Logging in...",
    authDivider: "or",
    authGoogleAction: "Continue with Google",
    authGoogleLoading: "Loading Google sign-in...",
    authGoogleWorking: "Signing in with Google...",
    authLogout: "Log out",
    authMenuLabel: "Open account menu",
    authPasswordNotice: "Default password",
    authPasswordDismiss: "Got it",
    authSignedInAs: "Signed in as",
    authSessionExpired: "Please log in again",
    authPasswordScreenTitle: "Save your password",
    authPasswordScreenBody: "This password will be needed the next time you log in. Save it somewhere safe before continuing.",
    authCopyPassword: "Copy password",
    authPasswordCopied: "Password copied",
    authContinueToApp: "Continue to app",
    authLogoutConfirmTitle: "Log out?",
    authLogoutConfirmBody: "You’ll need your saved password to log back in.",
    authCancel: "Cancel",
    authConfirmLogout: "Log out",
    helpLabel: "How it works",
    helpTranslate: "Start on the left: type a word or phrase, translate it, and add the result to your flashcards whenever you want to keep it.",
    helpGuess: "When a flashcard appears, pause for a moment and try to recall the translation before revealing it.",
    helpReview: "After you check the answer, tap \"Oops\" if you missed it or \"Got it\" if you knew it.",
    helpAdaptive: "Words you miss come back more often, so Oolpan focuses your time where it helps most."
  },
  he: {
    appName: "WordSketch",
    translateTab: "תרגום",
    studyTab: "כרטיסיות",
    swap: "החלפה",
    phraseLabel: "ביטוי",
    phrasePlaceholderEn: "הקלד או הקלידי באנגלית",
    phrasePlaceholderHe: "הקלד או הקלידי בעברית",
    translationPlaceholder: "תרגום",
    translateAction: "תרגום",
    translating: "מתרגם...",
    addFlashcard: "+ כרטיסייה",
    addingFlashcard: "יוצר כרטיסייה...",
    flashcardReady: "נשמר בחפיסה",
    flashcardRemoved: "הוסר מהכרטיסיות",
    suggestionAdded: "ההצעה נוספה לכרטיסיות",
    mockBanner: "מצב דמה פעיל.",
    studyHeading: "כרטיסיות",
    studyEmpty: "עדיין אין כרטיסיות. אפשר להוסיף ביטוי מלוח התרגום כדי להתחיל.",
    showAnswer: "ניחוש",
    gotIt: "יש!",
    oops: "לא בדיוק",
    aiModeMock: "מצב דמה",
    suggestionsHeading: "הצעות להמשך",
    suggestionsCaption: "מבוסס על חמש ההוספות האחרונות",
    suggestionsModalTitle: "קבלת הצעות",
    loadingSuggestions: "מחפש מילים קשורות...",
    suggestionsEmpty: "אחרי שמוסיפים כמה כרטיסיות, יופיעו כאן הצעות קשורות.",
    addSuggestion: "הוספה",
    removeFlashcard: "הסרה מהחפיסה",
    flashcardScore: "ציון",
    flashcardImageCue: "רמז חזותי",
    playAudio: "השמעת אודיו",
    autoSpeakHebrew: "השמעה אוטומטית בעברית",
    getSuggestions: "קבלת הצעות",
    close: "סגירה",
    learnedWords: "נלמדו",
    authTitle: "ברוכים הבאים ל-Oolpan",
    authLoginTab: "כניסה",
    authRegisterTab: "יצירת חשבון",
    authUsernameLabel: "שם משתמש",
    authUsernamePlaceholder: "בחרו שם משתמש",
    authPasswordLabel: "סיסמה",
    authPasswordPlaceholder: "הזינו סיסמה",
    authRegisterHint: "ניצור את החשבון ונפיק סיסמת ברירת מחדל לכניסות עתידיות.",
    authCreateAction: "יצירת חשבון",
    authCreating: "יוצר חשבון...",
    authLoginAction: "כניסה",
    authLoggingIn: "נכנס...",
    authDivider: "או",
    authGoogleAction: "המשך עם Google",
    authGoogleLoading: "טוען כניסה עם Google...",
    authGoogleWorking: "נכנס עם Google...",
    authLogout: "התנתקות",
    authMenuLabel: "פתיחת תפריט החשבון",
    authPasswordNotice: "סיסמת ברירת מחדל",
    authPasswordDismiss: "הבנתי",
    authSignedInAs: "מחובר בתור",
    authSessionExpired: "צריך להתחבר שוב",
    authPasswordScreenTitle: "כדאי לשמור את הסיסמה",
    authPasswordScreenBody: "הסיסמה הזאת תידרש בכניסה הבאה. כדאי לשמור אותה במקום בטוח לפני שממשיכים.",
    authCopyPassword: "העתקת סיסמה",
    authPasswordCopied: "הסיסמה הועתקה",
    authContinueToApp: "המשך לאפליקציה",
    authLogoutConfirmTitle: "להתנתק?",
    authLogoutConfirmBody: "כדי להיכנס שוב יהיה צריך את הסיסמה ששמרתם.",
    authCancel: "ביטול",
    authConfirmLogout: "התנתקות",
    helpLabel: "איך זה עובד",
    helpTranslate: "מתחילים בצד שמאל: מקלידים מילה או ביטוי, מתרגמים, ואז מוסיפים לכרטיסיות כל מה שרוצים לשמור.",
    helpGuess: "כשכרטיסייה מופיעה, עוצרים לרגע ומנסים להיזכר בתרגום לפני שחושפים אותו.",
    helpReview: "אחרי שבודקים את התשובה, בוחרים \"לא בדיוק\" אם טעיתם או \"יש!\" אם צדקתם.",
    helpAdaptive: "מילים שטעיתם בהן יחזרו לעיתים קרובות יותר, כדי ש-Oolpan ישקיע את הזמן בדיוק איפה שהכי עוזר."
  }
};

export function t(language: AppLanguage, key: string) {
  return copy[language][key] ?? key;
}
