import { adminDb } from "./database.js";
import { DEFAULT_ADAPTIVE_LEARNING_SCORE } from "../lib/scheduler.js";

let schemaInitializationPromise: Promise<void> | null = null;

async function createSchema() {
  await adminDb.begin(async (sql) => {
    await sql`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT NOT NULL,
        password_hash TEXT NOT NULL DEFAULT '',
        auth_provider TEXT NOT NULL DEFAULT 'local',
        google_sub TEXT,
        email TEXT,
        created_at TIMESTAMPTZ NOT NULL
      )
    `;

    await sql`
      CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_unique
      ON users (LOWER(username))
    `;

    await sql`
      CREATE UNIQUE INDEX IF NOT EXISTS users_google_sub_unique
      ON users (google_sub)
      WHERE google_sub IS NOT NULL
    `;

    await sql`
      CREATE TABLE IF NOT EXISTS user_sessions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token TEXT NOT NULL UNIQUE,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ NOT NULL
      )
    `;

    await sql`
      CREATE INDEX IF NOT EXISTS user_sessions_user_id_idx
      ON user_sessions (user_id)
    `;

    await sql.unsafe(`
      CREATE TABLE IF NOT EXISTS flashcards (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        source_text TEXT NOT NULL,
        source_language TEXT NOT NULL,
        target_text TEXT NOT NULL,
        target_language TEXT NOT NULL,
        part_of_speech TEXT NOT NULL,
        noun_gender TEXT,
        image_prompt TEXT NOT NULL,
        image_data TEXT,
        weight DOUBLE PRECISION NOT NULL DEFAULT ${DEFAULT_ADAPTIVE_LEARNING_SCORE},
        review_count INTEGER NOT NULL DEFAULT 0,
        mistake_count INTEGER NOT NULL DEFAULT 0,
        consecutive_correct INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL,
        last_reviewed_at TIMESTAMPTZ,
        last_result TEXT,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        UNIQUE (user_id, source_text, source_language, target_text, target_language)
      )
    `);

    await sql`
      CREATE INDEX IF NOT EXISTS flashcards_user_active_created_idx
      ON flashcards (user_id, is_active, created_at DESC)
    `;

    await sql`
      CREATE INDEX IF NOT EXISTS flashcards_user_last_reviewed_idx
      ON flashcards (user_id, last_reviewed_at)
    `;
  });
}

export function initializeSchema() {
  if (!schemaInitializationPromise) {
    schemaInitializationPromise = createSchema().catch((error) => {
      schemaInitializationPromise = null;
      throw error;
    });
  }

  return schemaInitializationPromise;
}
