import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { t } from "../lib/copy";
export function StudyPanel({ uiLanguage, card, isRevealed, isBusy, pendingReviewResult, isRemoving, onReveal, onReview, onRemove }) {
    const [menuOpen, setMenuOpen] = useState(false);
    useEffect(() => {
        setMenuOpen(false);
    }, [card?.id]);
    const score = card ? card.weight.toFixed(2) : null;
    return (_jsxs("section", { className: "panel review-panel", children: [_jsx("h2", { children: t(uiLanguage, "studyHeading") }), !card ? (_jsx("div", { className: "empty-state", children: t(uiLanguage, "studyEmpty") })) : (_jsxs("div", { className: "study-card-shell", children: [_jsxs("div", { className: "study-card", children: [_jsxs("div", { className: "study-card-menu", children: [_jsx("button", { className: "menu-trigger", type: "button", "aria-haspopup": "menu", "aria-expanded": menuOpen, onClick: () => setMenuOpen((current) => !current), children: "\u22EF" }), menuOpen ? (_jsxs("div", { className: "menu-popover", role: "menu", children: [_jsxs("div", { className: "menu-metric", children: [_jsx("span", { children: t(uiLanguage, "flashcardScore") }), _jsx("strong", { children: score })] }), _jsx("button", { className: "menu-action", type: "button", disabled: isBusy, onClick: onRemove, children: _jsxs("span", { className: "button-content", children: [isRemoving ? _jsx("span", { className: "button-spinner", "aria-hidden": "true" }) : null, _jsx("span", { children: t(uiLanguage, "removeFlashcard") })] }) })] })) : null] }), card.imageUrl ? _jsx("img", { className: "card-image", src: card.imageUrl, alt: card.imagePrompt }) : null, _jsx("div", { className: "prompt-block", children: isRevealed ? (_jsxs("div", { className: "revealed-compare", children: [_jsx("div", { className: "revealed-column", children: _jsx("p", { className: "prompt-text prompt-text-revealed", dir: card.promptLanguage === "he" ? "rtl" : "ltr", children: card.promptText }) }), _jsx("div", { className: "revealed-divider", "aria-hidden": "true" }), _jsx("div", { className: "revealed-column", children: _jsx("div", { className: "answer-block", children: _jsx("p", { dir: card.answerLanguage === "he" ? "rtl" : "ltr", children: card.answerText }) }) })] })) : (_jsx("p", { className: "prompt-text", dir: card.promptLanguage === "he" ? "rtl" : "ltr", children: card.promptText })) })] }), !isRevealed ? (_jsx("button", { className: "primary-button", type: "button", onClick: onReveal, children: t(uiLanguage, "showAnswer") })) : (_jsxs("div", { className: "review-actions", children: [_jsx("button", { className: "danger-button", type: "button", disabled: isBusy, onClick: () => onReview("oops"), children: _jsxs("span", { className: "button-content", children: [pendingReviewResult === "oops" ? _jsx("span", { className: "button-spinner", "aria-hidden": "true" }) : null, _jsx("span", { children: t(uiLanguage, "oops") })] }) }), _jsx("button", { className: "success-button", type: "button", disabled: isBusy, onClick: () => onReview("got_it"), children: _jsxs("span", { className: "button-content", children: [pendingReviewResult === "got_it" ? _jsx("span", { className: "button-spinner", "aria-hidden": "true" }) : null, _jsx("span", { children: t(uiLanguage, "gotIt") })] }) })] }))] }))] }));
}
